repos:
  - repo: local
    hooks:
      - id: mypy
        name: "[Type Checker] mypy"
        language: system
        entry: mypy --config-file=pyproject.toml
        types: [file, python]
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: ruff
        name: "[Lint & Format Checker] ruff"
        language: system
        entry: ruff check --config=pyproject.toml
        types: [file, python]
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: pytest
        name: "[Test] pytest"
        language: system
        entry: pytest -c pyproject.toml
        pass_filenames: false
        stages: [pre-push]
