repos:
  - repo: local
    hooks:
      - id: ty
        name: "[Type Checker] ty"
        language: system
        entry: ty check
        types: [file, python]
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: ruff
        name: "[Lint Checker] ruff"
        language: system
        entry: ruff check --config=pyproject.toml
        types: [file, python]
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: ruff
        name: "[Format Checker] ruff"
        language: system
        entry: ruff format --check --config=pyproject.toml
        types: [file, python]
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: pytest
        name: "[Test] pytest"
        language: system
        entry: pytest -c pyproject.toml
        pass_filenames: false
        stages: [pre-push]
