[project]
name = "fastapi-di-tpl"
version = "0.1.0"
description = "FastAPI with Dependency Injector Template"
readme = "README.md"
requires-python = ">=3.14, <3.15"
dependencies = [
    "dependency-injector",
    "fastapi[standard]",
    "loguru",
    "pydantic-settings",
]

[dependency-groups]
dev = [
    "ipykernel",
    "ruff",
    "ty",
    "prek",
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "pytest-env",
    "pytest-mock",
    "pytest-xdist",
    "types-pyyaml",
]

# ---------------------------------
# Type Checker
# ---------------------------------
[tool.ty.src]
include = ["src", "tests"]
exclude = [".venv"]

[tool.ty.rules]
possibly-missing-import = "ignore"
# ---------------------------------
# Formatter / Linter
# ---------------------------------
[tool.ruff]
line-length = 120
target-version = "py314"
exclude = [".venv"]

[tool.ruff.lint]
select = [
    "F",  # flake
    "I",  # isort
]
ignore = ["C901", "E501"]

[tool.ruff.lint.isort]
force-single-line = true

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E401"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

# ---------------------------------
# Test
# ---------------------------------
[tool.pytest.ini_options]
markers = [
    "e2e: End-to-end test",
    "integration: Combined entity test",
    "unit: Single entity",
]
asyncio_mode = "auto"
pythonpath = [
    "src",
    "tests",
]
testpaths = [
    "tests",
]
addopts = [
    "--numprocesses=auto",
    "--disable-warnings",
    "--cov",
    "--cov-config=.coveragerc",
    "--cov-report=term",
    "--cov-report=xml",
]
env = [
    "APP_ENV=test",
]
