name: "CI: Lint & Test"
on: [push]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint & Format"
    runs-on: ubuntu-24.04
    steps:
      #----------------------------------------------
      # Check out repo
      #----------------------------------------------
      - name: "Check out repository"
        uses: actions/checkout@v4
      #----------------------------------------------
      # Build & Cache environment
      #----------------------------------------------
      - name: "Install uv"
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: "Build project with uv"
        run: uv sync --locked --all-extras --dev
      #----------------------------------------------
      # Check Lint & Format
      #----------------------------------------------
      - name: "Lint & Format Check"
        run: |
          make check

  test:
    name: "Test"
    runs-on: ubuntu-24.04
    steps:
      #----------------------------------------------
      # Check out repo
      #----------------------------------------------
      - name: "Check out repository"
        uses: actions/checkout@v4
      #----------------------------------------------
      # Build & Cache environment
      #----------------------------------------------
      - name: "Install uv"
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: "Build project with uv"
        run: uv sync --locked --all-extras --dev
      #----------------------------------------------
      # Run tests
      #----------------------------------------------
      - name: "Run tests"
        run: |
          make test
