name: "CI: Lint & Test"
on: [push]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint & Format"
    runs-on: ubuntu-24.04
    steps:
      #----------------------------------------------
      # Check out repo
      #----------------------------------------------
      - name: "Check out repository"
        uses: actions/checkout@v4
      #----------------------------------------------
      # Build & Cache environment
      #----------------------------------------------
      - name: "Build & Cache with Poetry"
        uses: devbruce/poetry-build-action@1.0.0
        with:
          python-version: "3.12"
      #----------------------------------------------
      # Check Lint & Format
      #----------------------------------------------
      - name: "Lint & Format Check"
        run: |
          poetry run mypy --config-file=pyproject.toml .
          poetry run black --config=pyproject.toml --check .
          poetry run isort --sp=pyproject.toml --check .
          poetry run flake8 --toml-config=pyproject.toml .

  test:
    name: "Test"
    runs-on: ubuntu-24.04
    steps:
      #----------------------------------------------
      # Check out repo
      #----------------------------------------------
      - name: "Check out repository"
        uses: actions/checkout@v4
      #----------------------------------------------
      # Build & Cache environment
      #----------------------------------------------
      - name: "Build & Cache with Poetry"
        uses: devbruce/poetry-build-action@1.0.0
        with:
          python-version: "3.12"
      #----------------------------------------------
      # Run tests
      #----------------------------------------------
      - name: "Run tests"
        run: |
          poetry run pytest -c pyproject.toml
